---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.6
    attributes:
      golang:
        install_dir: '/usr'

suites:
  - name: default
    run_list:
      - recipe[consul::default]
    attributes:
      consul:
          datacenter: FortMeade
  - name: ui
    run_list:
      - recipe[consul::default]
      - recipe[consul::ui]
    attributes:
      consul:
         serve_ui: true
