
node:
  extends:
    file: docker-compose-common.yml
    service: node
  links:
    - rebar_api:rebar_api
{{ START ACCESS_MODE==FORWARDER }}
    - forwarder:forwarder
{{ END ACCESS_MODE==FORWARDER }}
