
revproxy:
  extends:
    file: docker-compose-common.yml
    service: revproxy
{{ START DEV_MODE }}
  volumes:
    - ./digitalrebar/digitalrebar-ux:/opt/digitalrebar-ux
{{ END DEV_MODE }}
{{ START ACCESS_MODE==FORWARDER }}
  links:
    - forwarder:forwarder
{{ END ACCESS_MODE==FORWARDER }}
{{ START ACCESS_MODE==HOST }}
  ports:
    - "443:443"
{{ END ACCESS_MODE==HOST }}

