
trust_me:
  extends:
    file: docker-compose-common.yml
    service: trust_me
{{ START ACCESS_MODE==FORWARDER }}
  net: "container:forwarder"
{{ END ACCESS_MODE==FORWARDER }}
{{ START ACCESS_MODE==HOST }}
  ports:
    - "8888:8888"
{{ END ACCESS_MODE==HOST }}

