<%
# Silly code to make sure that we have access to libs
require 'ostruct'
require "#{`pwd`.strip}/lib/consul_access.rb"
require 'httpclient'
Faraday.default_adapter = :httpclient

db = nil
while db.nil? do
  begin
    db = ConsulAccess.getService('rebar-database')
    username = ConsulAccess.getKey('digitalrebar/private/database/digitalrebar/username')
    password = ConsulAccess.getKey('digitalrebar/private/database/digitalrebar/password')
    database = ConsulAccess.getKey('digitalrebar/private/database/digitalrebar/database')
  rescue Exception => e
    STDERR.puts("Consul Access failed: #{e.message}")
    db = nil
  end
end

host = db.ServiceAddress
host = db.Address if host.nil? or host.empty?
host = "database" if host.nil? or host.empty?
port = db.ServicePort
port = 5432 if port.nil? or port == 0
%>
production:
  adapter: postgresql
  username: <%= username %>
  pool: 32
  timeout: 5000
  reaping_frequency: 3
  host: <%= host %>
  port: <%= port %>
  database: <%= database %>
  password: <%= password %>

development:
  adapter: postgresql
  username: <%= username %>
  pool: 32
  timeout: 5000
  reaping_frequency: 3
  host: <%= host %>
  port: <%= port %>
  database: <%= database %>
  password: <%= password %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: postgresql
  username: <%= username %>
  pool: 32
  timeout: 5000
  reaping_frequency: 3
  host: <%= host %>
  port: <%= port %>
  database: <%= database %>
  password: <%= password %>
